services:
  sender-api:
    build: .
    container_name: api-sender
    restart: unless-stopped
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "4242:4242"

    depends_on:
      - db
      - redis
  db:
    image: postgres:16-alpine
    container_name: db_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sender
      - POSTGRES_DB=sender
    volumes:
      - .docker/db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: db_redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=TRUE
