version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sender
      - POSTGRES_DB=api-sender
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: db_redis
    restart: always
    ports:
      - "6379:6379"
