version: "3.9"

services:
  app:
    build: .
    container_name: sender-api
    restart: always
    ports:
      - "4242:4242"
    environment:
      - DATABASE_URL=postgresql://postgres:sender@db:5432/postgres-sender
      - REDIS_HOST=db_redis
      - REDIS_PORT=6379
      - PORT=4242
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sender
      - POSTGRES_DB=postgres-sender
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: db_redis
    restart: always
    ports:
      - "6379:6379"
