const BETTER_AUTH_GOOGLE_CLIENT_ID =
  process.env.BETTER_AUTH_GOOGLE_CLIENT_ID! || "";
const BETTER_AUTH_GOOGLE_CLIENT_SECRET =
  process.env.BETTER_AUTH_GOOGLE_CLIENT_SECRET! || "";
const BETTER_AUTH_SECRET = process.env.BETTER_AUTH_SECRET! || "";
const BETTER_AUTH_REDIRECT_URI = process.env.BETTER_AUTH_REDIRECT_URI! || "";
const BETTER_AUTH_APP = process.env.BETTER_AUTH_APP! || "";

export {
  BETTER_AUTH_GOOGLE_CLIENT_ID,
  BETTER_AUTH_GOOGLE_CLIENT_SECRET,
  BETTER_AUTH_SECRET,
  BETTER_AUTH_REDIRECT_URI,
  BETTER_AUTH_APP,
};
